name: Continuous Integration

# Trigger this workflow on pull requests to protected branches
on:
  pull_request:
    branches:
      - devel
      - stage
      - prod

jobs:
  ci-pipeline:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15'
          cache: 'npm'
      
      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Linter (ESLint)
      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      # Step 5: Run Prettier Formatter
      - name: Run Prettier
        run: npm run prettier --write
        continue-on-error: false

      # Step 6: Run Tests (Jest)
      - name: Run Tests
        run: CI=true npm run test
        env:
          CI: true

      # Step 7: Build Application
      - name: Build Application
        run: npm run build

      # Step 8: Upload Build Artifacts1
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
          retention-days: 7
